spring:
  datasource:
    url: jdbc:mysql://192.168.0.21:3306/MallE-pms
    username: root
    password: 990312lycLYC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: MallE-ProductService
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.21:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.21

server:
  port: 10001
logging:
  level:
    cn.allwayz.product: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0

malle:
  thread:
    core-size: 20
    maximum-size: 200
    keep-alive-time: 10
    block-queue-size: 10000