spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://MallE-ProductService
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://MallE-ThirdPartyService
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://MallE-MemberService
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://MallE-WarehouseService
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://MallE-AdminService
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),//malle-admin/$\{segment}

        - id: malle_host_route
          uri: lb://MallE-ProductService
          predicates:
            - Host=malle.com, item.malle.com

        - id: malle_search_route
          uri: lb://MallE-SearchService
          predicates:
            - Host=search.malle.com

        - id: malle_auth_route
          uri: lb://MallE-AuthService
          predicates:
            - Host=auth.malle.com
