spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://MallE-ProductService
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: thirdparty_route
          uri: lb://MallE-ThirdPartyService
          predicates:
            - Path=/api/thirdparty/oss/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}


        - id: admin_route
          uri: lb://renrenFast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
