spring:
  application:
    name: MallE-SearchService
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.21:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.21
    port: 6379
  session:
    store-type: redis

server:
  port: 12000